if (WIN32)
	set(COMMON_LIBS opengl32 glu32)
elseif (APPLE)
	find_library(COCOA_FRAMEWORK Cocoa)
	find_library(OPENGL_FRAMEWORK OpenGL)
	find_library(CARBON_FRAMEWORK Carbon)
	find_library(IOKIT_FRAMEWORK IOKit)
	find_library(COREAUDIO_FRAMEWORK CoreAudio)
	find_library(COREVIDEO_FRAMEWORK CoreVideo)
	find_library(AVFOUNDATION_FRAMEWORK AVFoundation)
	mark_as_advanced(
		COCOA_FRAMEWORK 
		OPENGL_FRAMEWORK 
		CARBON_FRAMEWORK
		IOKIT_FRAMEWORK
		COREAUDIO_FRAMEWORK 
		COREVIDEO_FRAMEWORK 
		AVFOUNDATION_FRAMEWORK
	)
	set(COMMON_LIBS 
		${COMMON_LIBS} 
		${COCOA_FRAMEWORK} 
		${OPENGL_FRAMEWORK} 
		${CARBON_FRAMEWORK}
		${IOKIT_FRAMEWORK}
		${COREAUDIO_FRAMEWORK}
		${COREVIDEO_FRAMEWORK}
		${AVFOUNDATION_FRAMEWORK}
	)
endif ()

set(COMMON_INCLUDES ${COMMON_INCLUDES} ${CMAKE_SOURCE_DIR})